@api = http://localhost:3000/municipio
###
GET {{api}}

###
POST http://localhost:3000/municipio
Content-Type: application/json

{
    "Nombre_Municipio": "Pedro Xalapeño"
    
}

###
PUT http://localhost:3000/municipio/7
Content-Type: application/json

{
    "Nombre_Municipio": "CD Xalapa"
}


###
DELETE http://localhost:3000/municipio/4


//Municipio con un Id_Estado
###
POST http://localhost:3000/municipio
Content-Type: application/json

{
    "Nombre_Municipio": "Pedro Xalapeño",
    "Estado_Id" : "4"
    
}
